### ISSUE TITLE
Some events do not have a name

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/webcomp-events#25]

**Comment by lcfd** [comment]
@Piiit Hi, can you explain more extensively the outcome that we want to obtain?

**Comment by sseppi** [comment]
I've found that the "2° mercato delle Castagne a San Genesio" doesn't have the event name in English.

Probably the data provider didn't input the Event Title in English.

@lcfd @GnuRant can you please verify?

@lcfd @GnuRant @Piiit How do you suggest to solve the issue? Shall we not show the events that hasn't the translation in all selected languages? Shall we show the events only in the languages where we have the translation? Shall we keep it like it is now?

**Comment by lcfd** [comment]
Hi @sseppi ! I'll wait for @Piiit to check that the API are working correctly.
Once we'll know the problem we'll find a solution

**Comment by Piiit** [comment]
@lcfd The API is correct. Some content providers do not give all 3 languages, therefore some events do not have a title in some languages. We should implement a fallback... I suggest the following order:

1) English
2) Browser language setting
3) Other language not used in (1) or (2)

If the suggestion above is not feasible, do the following:

- Setting = English
1) English
2) Italian
3) German

- Setting = German
1) German
2) Italian
3) English

- Setting = Italian
1) Italian
2) German
3) English

**Comment by Piiit** [comment]
@lcfd Please follow the order above... English for locals might not be the right choice as first fallback.

**Comment by Piiit** [comment]
What new feature?

**Comment by lcfd** [comment]
German is not the right fallback, English is better.

fyi @sseppi

**Comment by sseppi** [comment]
@lcfd I know that normally German isn't the best fallback, but we have to consider also that in South Tyrol we have to deal also with the social and political context which sometimes imposes to go for sub-optimal solutions.

Moreover we have also to consider that the data often comes from small offices that do not have translators for the English content and knows only German and Italian. For this reason probably the most problematic language for the missing contents is English.

In any case I have already wrote also an email to IDM to check the content and increase the data quality.

I hope that I clarified a little bit more the reason because Peter proposed his solution.

**Comment by GnuRant** [comment]
@Piiit review

**Comment by Piiit** [comment]
@lcfd @sseppi In South Tyrol with a big part also Tourists from Germany/Austria, I guess German is a good fallback. But we would need statistics to be sure. Also pointers (especially in the mountains) in South Tyrol are often German only (for many historical reasons), and therefore also other foreign languages are best to consider German as fallback to match the digital world with the real counterpart.

**Comment by lcfd** [comment]
@Piiit I've already fixed the way you have proposed in the comment above. Give a look at the code.

**Comment by Piiit** [comment]
@lcfd I was about to check the functionality. The comment above was about an explanation why I consider my list a good solution
